import {STATUSES,DEFAULTS,round,dateISO,monthISO,rub,num,rows,orderStats,metrics,categoryStats,dailySeries,isActive,validate,csv,inMonth} from './core.mjs';
import {db,load,put,remove} from './data.js';
import {demoRecords} from './demo.js';
import {CONFIG} from './config.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={overview:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',orders:'<path d="M6 4h12v17H6zM9 4V2h6v2M9 9h6M9 13h6M9 17h3"/>',finance:'<rect x="3" y="5" width="18" height="15" rx="2"/><path d="M3 9h18M15 14h3"/>',tasks:'<path d="M8 6h13M8 12h13M8 18h13M3 5l1 1 2-3M3 11l1 1 2-3M3 17l1 1 2-3"/>',analytics:'<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="m10 2 4 0 1 3 3 1 3 3-1 3 1 3-3 3-3 1-1 3h-4l-1-3-3-1-3-3 1-3-1-3 3-3 3-1z"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.finance}</svg>`;
const VIEWS={overview:['Обзор','РАБОТА ПОД КОНТРОЛЕМ','Главные цифры, ближайшие сроки и точки роста.'],orders:['Заказы','ОТ ЗАЯВКИ ДО ОПЛАТЫ','Все работы, статусы и договоренности.'],finance:['Финансы','ДЕНЬГИ БЕЗ ДОГАДОК','Поступления, расходы и ожидаемая оплата.'],tasks:['Задачи','РАБОЧИЙ ПЛАН','Сроки заказов и конкретные действия.'],analytics:['Аналитика','ДОХОДНОСТЬ И ЭФФЕКТИВНОСТЬ','Какие работы приносят больше за час.'],settings:['Настройки','ТВОИ ОРИЕНТИРЫ','Цели, категории и данные кабинета.']};
let records=[],user=null,demo=false,view='overview',period=monthISO(),authMode='login',edit=null,deleting=null,busy=false,loaded=false,filter='',statusFilter='',categoryFilter='',financeTab='payments',taskTab='active',taskSearch='',refreshing=false,sessionGeneration=0;
const settings=()=>({...DEFAULTS,...records.find(r=>r.kind==='settings')?.data});
const rec=id=>records.find(r=>r.id===id);
const orders=()=>rows(records,'order');
const orderName=id=>orders().find(o=>o.id===id)?.title||'Общий расход';
const shortDate=d=>d?new Date(d+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'short'}):'Без даты';
const button=(label,action,id='',cls='btn')=>`<button class="${cls}" data-action="${action}"${id?` data-id="${esc(id)}"`:''}>${label}</button>`;
const badge=o=>`<span class="tag ${o.status}">${STATUSES[o.status]}</span>`;
const errorText=e=>{const m=e?.message||'Не удалось выполнить действие';if(/Invalid login credentials/i.test(m))return 'Проверь email и пароль.';if(/Email not confirmed/i.test(m))return 'Подтверди email по письму и войди снова.';if(/rate limit/i.test(m))return 'Слишком много запросов. Подожди несколько минут.';if(/fetch|network|timeout/i.test(m))return 'Нет связи с сервером. Ввод сохранен в форме. Проверь интернет и повтори.';if(/signup.*disabled/i.test(m))return 'Регистрация отключена. Используй существующий аккаунт.';if(/email.*not.*authorized|email_address_not_authorized/i.test(m))return 'Почтовая служба пока не принимает этот адрес. Используй существующий аккаунт планировщика.';return m;};
let toastTimer;
function toast(message,error=false){$('#toast').textContent=message;$('#toast').hidden=false;$('#toast').classList.toggle('error-toast',error);clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,6000);}
function empty(title,note,action='order',label='Добавить заказ'){return `<div class="empty"><div class="empty-symbol">□</div><h3>${esc(title)}</h3><p>${esc(note)}</p>${action?button(label,action):''}</div>`;}
function kpi(label,value,note,type='finance'){return `<div class="card kpi"><div class="kpi-label">${label}<span class="kpi-icon">${icon(type)}</span></div><div class="kpi-value money">${value}</div><div class="kpi-detail">${note}</div></div>`;}
function setSync(message,fail=false){$('#sync').textContent=message;$('#sync').classList.toggle('negative',fail);}
function render(){
 const [title,kicker,subtitle]=VIEWS[view];$('#crumb').textContent=title;$('#page-title').textContent=title;$('#page-kicker').textContent=kicker;$('#page-subtitle').textContent=subtitle;$('#period').value=period;$('#period').hidden=!['overview','finance','analytics'].includes(view);$('#new-order').hidden=view==='settings';
 $('#nav').innerHTML=Object.entries(VIEWS).map(([key,values])=>`<button class="nav-item ${view===key?'active':''}" data-action="nav" data-id="${key}" ${view===key?'aria-current="page"':''}>${icon(key)}<span>${values[0]}</span></button>`).join('');
 $('#account-name').textContent=settings().name;$('#avatar').textContent=settings().name.slice(0,1).toUpperCase();$('#account-email').textContent=demo?'Демонстрационный режим':user?.email||'';
 if(!loaded){$('#content').innerHTML=`<div class="card">${empty('Не удалось загрузить кабинет','Проверь интернет и нажми «Обновить». Изменение данных доступно после загрузки.','refresh','Обновить')}</div>`;return;}
 $('#content').innerHTML=({overview:renderOverview,orders:renderOrders,finance:renderFinance,tasks:renderTasks,analytics:renderAnalytics,settings:renderSettings}[view])();
 if(view==='analytics')calculateQuote();
}
function chart(){
 const series=dailySeries(records,period),all=series.flatMap(x=>[x.income,x.expense]),min=Math.min(0,...all),max=Math.max(1000,...all),range=max-min;
 const x=i=>50+i*(530/(series.length-1)),y=v=>190-((v-min)/range)*160,points=key=>series.map((s,i)=>`${x(i)},${y(s[key])}`).join(' ');
 return `<svg viewBox="0 0 610 230" class="chart" role="img" aria-label="Поступления и расходы по дням месяца">${Array.from({length:4},(_,i)=>{const v=min+range*i/3,yy=y(v);return `<line x1="50" x2="592" y1="${yy}" y2="${yy}" stroke="#e9e8ed" stroke-dasharray="3 5"/><text x="41" y="${yy+4}" text-anchor="end">${num(v/1000)}к</text>`;}).join('')}<polyline points="${points('expense')}" fill="none" stroke="#bac3cf" stroke-width="2"/><polyline points="${points('income')}" fill="none" stroke="#7763c7" stroke-width="2.7" stroke-linecap="round" stroke-linejoin="round"/>${series.filter((_,i)=>i%5===0||i===series.length-1).map(s=>`<text x="${x(s.day-1)}" y="218" text-anchor="middle">${s.day}</text>`).join('')}</svg>`;
}
function focusList(list){return list.length?list.map(o=>{const overdue=isActive(o)&&o.deadline<dateISO();return `<div class="focus-row"><div><a href="#" class="focus-title" data-action="order" data-id="${o.id}">${esc(o.title)}</a><span class="focus-note">${esc(o.client||o.category)} · ${shortDate(o.deadline)}</span></div>${overdue?'<span class="tag overdue">Просрочен</span>':badge(o)}</div>`;}).join(''):'<p class="muted small">Ближайших дедлайнов пока нет.</p>';}
function renderOverview(){
 const m=metrics(records,period),s=settings(),pct=s.goal?Math.min(100,Math.max(0,m.cash/s.goal*100)):0,urgent=orders().filter(isActive).sort((a,b)=>a.deadline.localeCompare(b.deadline)).slice(0,4),debts=orders().filter(o=>orderStats(o,records).outstanding>0&&['done','delivered'].includes(o.status)).sort((a,b)=>orderStats(b,records).outstanding-orderStats(a,records).outstanding).slice(0,3);
 return `<div class="kpi-grid">${kpi('Получено за месяц',rub(m.revenue),'Поступления за вычетом возвратов')}${kpi('Денежный результат',rub(m.cash),'Получено минус расходы, до налогов')}${kpi('Ожидается оплата',rub(m.outstanding),'По всем неотмененным заказам')}${kpi('Час работы',m.rate===null?'Нет данных':rub(m.rate),`${num(m.minutes/60)} ч учтено за месяц`,'clock')}</div>
 <div class="dashboard-grid"><div class="stack"><section class="card"><div class="card-header"><div><h2>Движение денег</h2><p>По дням выбранного месяца</p></div><div class="chart-legend"><span>Поступления</span><span>Расходы</span></div></div>${chart()}</section><section class="card"><div class="card-header"><div><h2>Ближайшие сроки</h2><p>${m.active.length} заказов в работе${m.overdue.length?` · ${m.overdue.length} просрочено`:''}</p></div>${button('Все заказы','nav','orders','link')}</div>${focusList(urgent)}${!orders().length?empty('Начни с первого заказа','Добавь стоимость, комиссию и срок. После первого платежа здесь появятся реальные цифры.') : ''}</section></div>
 <div class="stack"><section class="card goal-card"><p class="eyebrow">ФИНАНСОВЫЙ ОРИЕНТИР</p><h2>Цель на месяц</h2><div class="goal-amount">${rub(m.cash)}</div><div class="goal-total">${s.goal?`из ${rub(s.goal)} денежного результата`:'Задай сумму в настройках'}</div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><div class="goal-bottom"><span>${s.goal?`${Math.round(pct)}% цели`:'Цель пока не задана'}</span><span>${s.goal?`Осталось ${rub(Math.max(0,s.goal-m.cash))}`:'До налогов'}</span></div>${button('Изменить ориентир','nav','settings','link')}</section>
 <section class="card"><div class="card-header"><h2>Пора получить оплату</h2></div>${debts.length?debts.map(o=>`<div class="focus-row"><div><span class="focus-title">${esc(o.title)}</span><span class="focus-note">${esc(o.client||'Клиент не указан')}</span></div><div><div class="amount">${rub(orderStats(o,records).outstanding)}</div>${button('Оплата','payment',o.id,'link')}</div></div>`).join(''):'<p class="muted small">Сданных заказов с остатком оплаты нет.</p>'}</section>
 <section class="card"><div class="card-header"><h2>Следующий шаг</h2></div>${suggestions(m).slice(0,2).map((h,i)=>`<div class="hint-item ${i?'section-gap':''}"><span class="hint-num">0${i+1}</span><div><h3>${h.title}</h3><p>${h.text}</p></div></div>`).join('')}</section></div></div>`;
}
function suggestions(m){
 const s=settings(),cat=categoryStats(records,period),h=[];
 if(m.overdue.length)h.push({title:'Разгрузить просроченные заказы',text:`Срок прошел у ${m.overdue.length} работ. Сначала уточни с заказчиками новый срок и объем оставшихся действий.`});
 const debt=orders().filter(o=>['done','delivered'].includes(o.status)&&orderStats(o,records).outstanding>0);if(debt.length)h.push({title:'Закрыть ожидаемую оплату',text:`По сданным работам ожидается ${rub(debt.reduce((a,o)=>a+orderStats(o,records).outstanding,0))}. Проверь, что клиент принял результат и площадка разрешила выплату.`});
 if(m.rework&&m.minutes&&m.rework/m.minutes>.2)h.push({title:'Уточнить условия доработок',text:`Доработки заняли ${Math.round(m.rework/m.minutes*100)}% учтенного времени. Проверь причины правок и заранее согласуй, какие изменения входят в цену.`});
 const weak=cat.filter(c=>c.rate!==null&&s.hourly&&c.rate<s.hourly&&c.count>=3);if(weak.length)h.push({title:'Пересмотреть цену категории',text:`«${esc(weak[0].category)}»: ${rub(weak[0].rate)} за час на ${weak[0].count} завершенных заказах при твоем ориентире ${rub(s.hourly)}. Проверь трудоемкость новых заказов калькулятором.`});
 if(!rows(records,'time').length)h.push({title:'Начать учитывать время',text:'Запиши время хотя бы по нескольким заказам, отдельно отмечая доработки. Тогда станет видно, куда уходит рабочий день.'});
 if(!s.hourly)h.push({title:'Задать стоимость своего часа',text:'Укажи минимальный доход за час в настройках. Кабинет сможет сравнивать категории с твоим ориентиром.'});
 if(!h.length)h.push({title:'Сравнить категории работ',text:'Открой аналитику и сопоставь прибыль за час. Для выводов используй несколько завершенных заказов, а не одну удачную работу.'});
 return h;
}
function filteredOrders(){return orders().filter(o=>(!filter||`${o.title} ${o.client} ${o.notes}`.toLowerCase().includes(filter.toLowerCase()))&&(!statusFilter||o.status===statusFilter)&&(!categoryFilter||o.category===categoryFilter)).sort((a,b)=>{const aa=isActive(a),bb=isActive(b);return Number(bb)-Number(aa)||a.deadline.localeCompare(b.deadline);});}
function orderTable(list){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Заказ / клиент</th><th>Статус</th><th>Срок</th><th>К получению</th><th>Остаток</th><th>Прибыль / час</th><th></th></tr></thead><tbody>${list.map(o=>{const s=orderStats(o,records);return `<tr><td class="wrap"><span class="row-title">${esc(o.title)}</span><span class="row-sub">${esc(o.client||'Без клиента')} · ${esc(o.category)}</span></td><td>${badge(o)}</td><td class="${isActive(o)&&o.deadline<dateISO()?'negative':''}">${shortDate(o.deadline)}</td><td class="money">${rub(s.net)}</td><td class="money">${rub(s.outstanding)}</td><td class="money ${settings().hourly&&s.rate!==null&&s.rate<settings().hourly?'negative':''}">${s.rate===null?'Нет данных':rub(s.rate)}<span class="row-sub">${num(s.minutes/60)} ч${isActive(o)?' · предварительно':''}</span></td><td><div class="actions">${button('Открыть','order',o.id,'table-btn')}${button('Оплата','payment',o.id,'table-btn')}</div></td></tr>`;}).join('')}</tbody></table></div>`;}
function renderOrders(){const list=filteredOrders();return `<div class="toolbar"><input class="search" id="order-search" aria-label="Поиск заказов" placeholder="Поиск по заказу, клиенту или примечанию" value="${esc(filter)}"><select id="status-filter" aria-label="Статус"><option value="">Все статусы</option>${Object.entries(STATUSES).map(([key,val])=>`<option value="${key}" ${statusFilter===key?'selected':''}>${val}</option>`).join('')}</select><select id="category-filter" aria-label="Категория"><option value="">Все категории</option>${[...new Set([...settings().categories,...orders().map(o=>o.category)])].map(c=>`<option ${categoryFilter===c?'selected':''}>${esc(c)}</option>`).join('')}</select>${button('Скачать CSV','csv','','btn')}</div><section class="card"><div class="card-header"><h2>Реестр заказов <span class="muted">${list.length}</span></h2><span class="small muted">Все периоды</span></div>${list.length?orderTable(list):empty(orders().length?'Нет совпадений':'Заказы пока не добавлены',orders().length?'Измени поиск или фильтры.':'Создай карточку первого заказа. Стоимость и комиссия будут учитываться отдельно.',orders().length?'':'order')}<p class="sort-note">Прибыль заказа = стоимость минус комиссия и связанные расходы. Налоги не включены.</p></section>`;}
function renderFinance(){
 const m=metrics(records,period),all=financeTab==='payments'?rows(records,'payment'):financeTab==='expenses'?rows(records,'expense'):orders().filter(o=>orderStats(o,records).outstanding>0);
 const list=financeTab==='debts'?all:all.filter(r=>inMonth(r.date,period)).sort((a,b)=>b.date.localeCompare(a.date));
 return `<div class="kpi-grid">${kpi('Поступления',rub(m.revenue),'За вычетом возвратов')}${kpi('Расходы',rub(m.cost),'Общие и связанные с заказами')}${kpi('Денежный результат',rub(m.cash),'До налогов')}${kpi('Ожидается',rub(m.outstanding),'По всем периодам')}</div><div class="notice">В платежах записывай сумму, фактически поступившую тебе после удержания комиссии. Комиссию укажи в карточке заказа; второй раз в расходы ее добавлять не нужно.</div><section class="card"><div class="tabs">${[['payments','Поступления и возвраты'],['expenses','Расходы'],['debts','Ожидаемая оплата']].map(([k,v])=>button(v,'finance-tab',k,'tab '+(financeTab===k?'active':''))).join('')}</div><div class="card-header"><h2>${financeTab==='payments'?'Платежи':financeTab==='expenses'?'Расходы':'Заказы с остатком оплаты'}</h2>${button(financeTab==='expenses'?'+ Расход':'+ Платеж',financeTab==='expenses'?'expense':'payment')}</div>${financeTab==='debts'?(list.length?orderTable(list):empty('Ожидаемой оплаты нет','Вся сумма по неотмененным заказам получена.','')):(list.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Дата</th><th>${financeTab==='expenses'?'Категория':'Вид'}</th><th>Заказ</th><th>Сумма</th><th>Примечание</th><th></th></tr></thead><tbody>${list.map(p=>`<tr><td>${shortDate(p.date)}</td><td>${esc(financeTab==='expenses'?p.category:p.type==='refund'?'Возврат':'Поступление')}</td><td class="wrap">${esc(orderName(p.orderId))}</td><td class="money ${p.type==='refund'?'negative':''}">${p.type==='refund'?'-':''}${rub(p.amount)}</td><td class="wrap muted">${esc(p.notes)}</td><td><div class="actions">${button('Изменить','edit-record',p.id,'table-btn')}${button('Удалить','delete',p.id,'table-btn')}</div></td></tr>`).join('')}</tbody></table></div>`:empty('Записей за месяц нет','Добавь фактическое поступление или расход. Плановая стоимость заказа здесь не считается полученными деньгами.',financeTab==='expenses'?'expense':'payment',financeTab==='expenses'?'Добавить расход':'Добавить платеж'))}</section>`;
}
function renderTasks(){
 const today=dateISO(),tasks=rows(records,'task').filter(t=>taskTab==='done'?t.done:!t.done).filter(t=>!taskSearch||`${t.title} ${t.notes}`.toLowerCase().includes(taskSearch.toLowerCase())).sort((a,b)=>a.deadline.localeCompare(b.deadline)||({high:0,normal:1,low:2}[a.priority]-{high:0,normal:1,low:2}[b.priority]));
 const active=orders().filter(isActive).sort((a,b)=>a.deadline.localeCompare(b.deadline));
 if(taskTab==='calendar'){const dates=[...new Set([...active.map(o=>o.deadline),...rows(records,'task').filter(t=>!t.done).map(t=>t.deadline)])].sort();return `<div class="toolbar">${button('Задачи','task-tab','active')}${button('Календарь сроков','task-tab','calendar','btn primary')}${button('+ Задача','task','','btn')}</div><div class="calendar">${dates.length?dates.map(d=>`<section class="calendar-day"><div class="calendar-date ${d<today?'negative':''}">${shortDate(d)} ${d<today?'· срок прошел':''}</div><div class="calendar-content">${focusList(active.filter(o=>o.deadline===d))}${rows(records,'task').filter(t=>!t.done&&t.deadline===d).map(t=>`<div class="focus-row"><span class="focus-title">${esc(t.title)}</span>${button('Открыть','edit-record',t.id,'table-btn')}</div>`).join('')}</div></section>`).join(''):`<div class="card">${empty('Календарь свободен','Добавь заказ или задачу со сроком.','task','Добавить задачу')}</div>`}</div>`;}
 return `<div class="toolbar"><input id="task-search" class="search" aria-label="Поиск задач" placeholder="Найти задачу" value="${esc(taskSearch)}">${button('Календарь сроков','task-tab','calendar')}${button('+ Задача','task')}</div><div class="tabs">${button('Активные','task-tab','active','tab '+(taskTab==='active'?'active':''))}${button('Выполненные','task-tab','done','tab '+(taskTab==='done'?'active':''))}</div><div class="task-list">${tasks.length?tasks.map(t=>`<div class="task-card ${t.done?'done':''}"><button class="task-toggle" data-action="toggle-task" data-id="${t.id}" aria-label="${t.done?'Вернуть в работу':'Выполнить'}: ${esc(t.title)}">${t.done?'✓':''}</button><div class="task-content"><div class="task-title">${esc(t.title)}</div><div class="task-meta"><span class="${!t.done&&t.deadline<today?'negative':''}">${shortDate(t.deadline)}</span><span>${{high:'Высокий приоритет',normal:'Обычный приоритет',low:'Низкий приоритет'}[t.priority]}</span>${t.orderId?`<span>${esc(orderName(t.orderId))}</span>`:''}</div>${t.notes?`<p class="small muted" style="margin:9px 0 0">${esc(t.notes)}</p>`:''}</div><div class="task-actions">${button('Изменить','edit-record',t.id,'table-btn')}${button('Удалить','delete',t.id,'table-btn')}</div></div>`).join(''):`<div class="card">${empty('В этом списке задач нет','Добавляй конкретные шаги: проверить источники, внести правки или уточнить оплату.','task','Добавить задачу')}</div>`}</div><section class="card section-gap"><div class="card-header"><h2>Дедлайны заказов</h2><span class="small muted">Активные работы</span></div>${focusList(active.slice(0,6))}</section>`;
}
function renderAnalytics(){
 const m=metrics(records,period),s=settings(),cat=categoryStats(records,period),time=rows(records,'time').filter(t=>inMonth(t.date,period)).sort((a,b)=>b.date.localeCompare(a.date));
 const in7=new Date(dateISO()+'T12:00:00Z');in7.setUTCDate(in7.getUTCDate()+7);const week=in7.toISOString().slice(0,10),due=orders().filter(o=>isActive(o)&&o.deadline<=week),planned=round(due.reduce((a,o)=>a+Math.max(0,o.estimate-orderStats(o,records).minutes/60),0));
 const clients=[...new Set(orders().map(o=>o.client).filter(Boolean))].map(client=>{const list=orders().filter(o=>o.client===client&&o.status!=='cancelled');return {client,count:list.length,profit:round(list.reduce((a,o)=>a+(o.status==='done'?orderStats(o,records).profit:0),0))};}).sort((a,b)=>b.count-a.count).slice(0,5);
 return `<div class="mini-metrics">${kpi('Завершено заказов',m.completed,`Прибыль заказов: ${rub(m.earned)}`,'orders')}${kpi('Сдано в срок',m.onTime===null?'Нет данных':m.onTime+'%','По дате первой сдачи в этом месяце','tasks')}${kpi('Доля доработок',m.minutes?Math.round(m.rework/m.minutes*100)+'%':'Нет данных',`${num(m.rework/60)} ч на правки из ${num(m.minutes/60)} ч`,'clock')}</div>
 <section class="card"><div class="card-header"><div><h2>Доходность категорий</h2><p>Завершенные в выбранном месяце заказы. Расходы и время за весь срок заказа.</p></div></div>${cat.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Категория</th><th>Заказов</th><th>Прибыль</th><th>Время</th><th>Прибыль / час</th><th>Средняя прибыль</th></tr></thead><tbody>${cat.map(c=>`<tr><td>${esc(c.category)}</td><td>${c.count}</td><td>${rub(c.profit)}</td><td>${num(c.minutes/60)} ч</td><td class="${s.hourly&&c.rate!==null&&c.rate<s.hourly?'negative':'positive'}">${c.rate===null?'Нет данных':rub(c.rate)}</td><td>${rub(c.average)}</td></tr>`).join('')}</tbody></table></div>`:empty('Для сравнения нужны завершенные заказы','Когда работа закончена, выбери статус «Завершен», укажи дату завершения и запиши потраченное время.','')}<p class="formula">Прибыль за час = (стоимость - комиссия - расходы заказа) / фактические часы, включая доработки. Общие подписки и налоги в показатель категории не входят. Один заказ дает только предварительный ориентир.</p></section>
 <div class="two-col section-gap"><section class="card"><div class="card-header"><h2>Калькулятор цены</h2></div><div class="calculator"><label>Ожидаемое время, ч<input id="calc-hours" type="number" min="0" step="0.5" value="5"></label><label>Твой час, руб.<input id="calc-rate" type="number" min="0" step="50" value="${s.hourly}"></label><label>Расходы заказа, руб.<input id="calc-cost" type="number" min="0" value="0"></label><label>Комиссия площадки, %<input id="calc-fee" type="number" min="0" max="99" step="0.1" value="0"></label><div class="calculator-output"><span>Цена для выбранного дохода за час</span><strong id="quote-result">-</strong></div></div><p class="formula">Цена = (часы × доход за час + расходы) / (1 - комиссия / 100). Укажи фактическую комиссию своей площадки. Налоги в расчет не входят.</p></section><section class="card"><div class="card-header"><h2>Загрузка на 7 дней</h2></div><div class="goal-amount">${num(planned)} <span class="muted" style="font-size:16px;letter-spacing:0">из ${num(s.weeklyHours)} ч</span></div><div class="progress-track" style="background:#e8e5ef"><div class="progress-fill" style="width:${s.weeklyHours?Math.min(100,planned/s.weeklyHours*100):0}%;background:${planned>s.weeklyHours?'#b64251':'#7763c7'}"></div></div><p class="formula">Остаток планового времени по активным заказам со сроком в ближайшие 7 дней и просроченным работам. План минус уже учтенные часы. Задачи отдельно в нагрузку не включены.</p>${planned>s.weeklyHours?'<div class="notice danger section-gap">План превышает доступное время. Проверь приоритеты и сроки до принятия нового заказа.</div>':''}<div class="divider"></div><h3>Рабочие ориентиры</h3><div class="hint-list section-gap">${suggestions(m).map((h,i)=>`<div class="hint-item"><span class="hint-num">${i+1}</span><div><h3>${h.title}</h3><p>${h.text}</p></div></div>`).join('')}</div></section></div>
 <section class="card section-gap"><div class="card-header"><div><h2>Рабочее время</h2><p>Записывай работу и доработки отдельно</p></div>${button('+ Записать время','time')}</div><div class="time-summary"><div><strong>${num((m.minutes-m.rework)/60)} ч</strong><span>Основная работа</span></div><div><strong>${num(m.rework/60)} ч</strong><span>Доработки</span></div></div>${time.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Дата</th><th>Заказ</th><th>Вид работы</th><th>Время</th><th></th></tr></thead><tbody>${time.map(t=>`<tr><td>${shortDate(t.date)}</td><td class="wrap">${esc(orderName(t.orderId))}</td><td>${t.type==='rework'?'Доработка':'Основная работа'}</td><td>${num(t.minutes/60)} ч</td><td><div class="actions">${button('Изменить','edit-record',t.id,'table-btn')}${button('Удалить','delete',t.id,'table-btn')}</div></td></tr>`).join('')}</tbody></table></div>`:empty('Время за месяц не записано','Добавь фактическую длительность работы, чтобы увидеть доход за час.','time','Записать время')}</section>
 <section class="card section-gap"><div class="card-header"><div><h2>Клиенты</h2><p>По всем периодам, без отмененных заказов</p></div></div>${clients.length?clients.map(c=>`<div class="client-item"><div><h3>${esc(c.client)}</h3><p>${c.count} заказов${c.count>1?' · повторный клиент':''}</p></div><div class="money">${rub(c.profit)}<p>прибыль завершенных работ</p></div></div>`).join(''):'<p class="muted small">Укажи клиента в карточке заказа, чтобы отслеживать повторные обращения.</p>'}</section>`;
}
function calculateQuote(){const vals=['hours','rate','cost','fee'].map(k=>+$('#calc-'+k)?.value);if(vals.some(x=>!Number.isFinite(x)||x<0)||vals[3]>=100){$('#quote-result').textContent='Проверь значения';return;}$('#quote-result').textContent=vals[0]&&vals[1]?rub(round((vals[0]*vals[1]+vals[2])/(1-vals[3]/100))):'Задай время и ставку';}
function renderSettings(){const s=settings();return `<div class="two-col"><section class="card"><div class="card-header"><h2>Профиль и цели</h2></div><form class="settings-form" id="settings-form"><label>Название кабинета<input name="name" maxlength="100" value="${esc(s.name)}" required></label><div class="row"><label>Цель на месяц, руб.<input name="goal" type="number" min="0" step="100" value="${s.goal}" required></label><label>Минимальный доход за час, руб.<input name="hourly" type="number" min="0" step="50" value="${s.hourly}" required></label></div><label>Доступное время в неделю, ч<input name="weeklyHours" type="number" min="0" max="168" step="0.5" value="${s.weeklyHours}" required></label><label>Категории заказов - по одной на строку<textarea name="categories" required>${esc(s.categories.join('\n'))}</textarea></label><p class="small muted">Изменение списка не меняет категории старых заказов. Финансовая цель относится к денежному результату до налогов.</p><p class="error" id="settings-error" role="alert"></p><button class="btn primary" type="submit">Сохранить настройки</button></form></section><section class="card"><div class="card-header"><h2>Аккаунт и данные</h2></div><div class="settings-section"><h3>Синхронизация</h3><p>${demo?'Открыт вымышленный пример. Изменения не сохраняются.':'Заказы, платежи, расходы, задачи, время и настройки сохраняются в твоем аккаунте. Войди с тем же email на телефоне и компьютере. Обновление происходит при возвращении во вкладку и каждые 30 секунд.'}</p><p class="small">При отсутствии интернета запись не считается сохраненной. Кабинет оставляет ввод в форме, чтобы ты мог повторить действие.</p>${button('Обновить данные','refresh')}</div><div class="settings-section"><h3>Выгрузка</h3><p>CSV открывается в Excel и содержит все заказы. JSON сохраняет полную копию записей без пароля и ключей входа.</p>${button('Заказы в CSV','csv')}${button('Полная копия JSON','export')}</div><div class="settings-section"><h3>Доступ</h3><p>У других пользователей нет доступа к твоим записям. На общем компьютере выходи из аккаунта после работы.</p>${button(demo?'Войти в свой аккаунт':'Выйти из аккаунта','logout')}</div><div class="settings-section"><h3>Как читать показатели</h3><p>Получено - фактические поступления минус возвраты. Денежный результат - получено минус расходы за месяц. Прибыль заказа - цена минус комиссия и связанные расходы, независимо от оплаты. Все показатели рассчитываются до налогов.</p><p>Выплаты, комиссии и сроки площадки ты вносишь вручную. Автоматического подключения к «Все сдал» нет.</p></div></section></div>`;}
const input=(name,label,value='',type='text',extra='',span=false)=>`<label class="${span?'span-two':''}">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(name,label,options,value,span=false)=>`<label class="${span?'span-two':''}">${label}<select name="${name}" aria-label="${esc(label)}">${options.map(([v,t])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
const notes=(value='')=>`<label class="span-two">Примечание<textarea name="notes" maxlength="10000">${esc(value)}</textarea></label>`;
function orderPicker(value='',required=false){return select('orderId','Заказ',[[ '',required?'Выбери заказ':'Без привязки к заказу'],...orders().map(o=>[o.id,o.title])],value,true);}
function openEditor(kind,id='',linked=''){
 if(!loaded)return toast('Сначала загрузи данные кабинета',true);if(demo)return toast('Пример доступен для просмотра. Войди, чтобы добавлять записи.');
 const old=id?rec(id):null,d=old?.data||{},labels={order:'заказ',payment:'платеж',expense:'расход',time:'учет времени',task:'задачу'};edit={kind,old};$('#editor-title').textContent=kind==='order'?(old?'Карточка заказа':'Новый заказ'):`${old?'Изменить':'Добавить'} ${labels[kind]}`;$('#editor-kicker').textContent=labels[kind].toUpperCase();$('#editor-error').textContent='';
 let fields='';
 if(kind==='order'){
  const s=old?orderStats({...d,id:old.id},records):null;
  fields=(s?`<div class="detail-strip span-two"><div><strong>${rub(s.received)}</strong><span>Получено</span></div><div><strong>${rub(s.outstanding)}</strong><span>Ожидается</span></div><div><strong>${num(s.minutes/60)} ч</strong><span>Фактическое время</span></div></div><div class="span-two toolbar">${button('Записать оплату','related-payment',old.id)}${button('Записать время','related-time',old.id)}${button('Добавить расход','related-expense',old.id)}${button('Удалить заказ','delete',old.id,'btn')}</div>`:'')+
  input('title','Название заказа',d.title,'text','required maxlength="250"',true)+input('client','Клиент',d.client,'text','maxlength="250"')+select('category','Категория',[...new Set([...settings().categories,...(d.category?[d.category]:[])])].map(c=>[c,c]),d.category||settings().categories[0])+input('price','Стоимость до комиссии, руб.',d.price??'','number','min="0" step="0.01" required')+input('fee','Комиссия площадки, руб.',d.fee??0,'number','min="0" step="0.01" required')+select('status','Статус',Object.entries(STATUSES),d.status||'new')+input('deadline','Срок сдачи',d.deadline||dateISO(),'date','required')+input('date','Дата принятия заказа',d.date||dateISO(),'date','required')+input('estimate','Плановое время, ч',d.estimate??0,'number','min="0" step="0.5" required')+input('deliveredDate','Дата первой сдачи',d.deliveredDate||'','date')+input('completedDate','Дата завершения',d.completedDate||'','date')+input('source','Источник / площадка',d.source??'Все сдал','text','maxlength="100"')+input('revisions','Количество доработок',d.revisions??0,'number','min="0" step="1" required')+input('url','Ссылка на заказ',d.url||'','url','placeholder="https://..."',true)+notes(d.notes)+`<p class="inline-note">«Сдан» означает передачу результата, «Завершен» - окончание работы. Оплата записывается отдельно. При выборе этих статусов дата подставится, если поле пустое.</p>`;
 }else if(kind==='payment') fields=orderPicker(d.orderId||linked,true)+select('type','Вид платежа',[['receipt','Поступление'],['refund','Возврат заказчику']],d.type||'receipt')+input('amount','Фактическая сумма, руб.',d.amount??'','number','min="0.01" step="0.01" required')+input('date','Дата',d.date||dateISO(),'date','required')+notes(d.notes)+`<p class="inline-note">Поступление указывай после удержания комиссии. Предоплату можно записывать частями. Возврат уменьшает фактически полученную сумму.</p>`;
 else if(kind==='expense') fields=select('category','Категория расхода',['Сервисы и подписки','Проверка оригинальности','Материалы и источники','Помощь исполнителя','Другие расходы',...(d.category?[d.category]:[])].filter((x,i,a)=>a.indexOf(x)===i).map(c=>[c,c]),d.category||'Сервисы и подписки')+input('amount','Сумма, руб.',d.amount??'','number','min="0.01" step="0.01" required')+orderPicker(d.orderId||linked)+input('date','Дата',d.date||dateISO(),'date','required')+notes(d.notes)+`<p class="inline-note">Расход с привязкой уменьшает прибыль конкретного заказа. Общая подписка уменьшает денежный результат месяца.</p>`;
 else if(kind==='time') fields=orderPicker(d.orderId||linked)+select('type','Вид работы',[['work','Основная работа'],['rework','Доработка']],d.type||'work')+input('minutes','Длительность, минут',d.minutes??'','number','min="1" max="1440" step="1" required')+input('date','Дата',d.date||dateISO(),'date','required')+notes(d.notes)+`<p class="inline-note">За одну запись - до 24 часов. Непривязанное время учитывается в месячной ставке, но не в доходности категории.</p>`;
 else if(kind==='task') fields=input('title','Что нужно сделать',d.title,'text','required maxlength="250"',true)+input('deadline','Срок',d.deadline||dateISO(),'date','required')+select('priority','Приоритет',[['high','Высокий'],['normal','Обычный'],['low','Низкий']],d.priority||'normal')+orderPicker(d.orderId||linked)+notes(d.notes);
 $('#editor-fields').innerHTML=fields;$('#editor').showModal();setTimeout(()=>$('#editor-fields input, #editor-fields select')?.focus(),30);
}
function paymentChecks(data,old=null,kind='payment'){
 const list=rows(records,'payment').filter(p=>p.orderId===data.orderId&&p.id!==old?.id),net=list.reduce((a,p)=>round(a+(p.type==='refund'?-p.amount:p.amount)),0),next=round(net+(data.type==='refund'?-data.amount:data.amount)),o=orders().find(x=>x.id===data.orderId);
 if(!o)throw Error('Выбери существующий заказ');if(next<-.009)throw Error('Возврат превышает сумму поступлений по заказу');if(next>orderStats(o,records).net+.009)throw Error('Поступления превышают сумму к получению по заказу. Проверь стоимость, комиссию и уже записанные платежи.');
}
async function saveEditor(event){event.preventDefault();if(busy)return;const form=new FormData($('#editor-form')),d=Object.fromEntries(form),{kind,old}=edit;busy=true;$('#editor-save').disabled=true;$('#editor-error').textContent='';
 try{
  if(kind==='order') {for(const k of ['price','fee','estimate','revisions'])d[k]=+d[k];d.title=d.title.trim();if(['delivered','done'].includes(d.status)&&!d.deliveredDate)d.deliveredDate=dateISO();if(d.status==='done'&&!d.completedDate)d.completedDate=dateISO();if(d.status!=='done')d.completedDate='';if(old&&d.price-d.fee<orderStats({...old.data,id:old.id},records).received)throw Error('Новая сумма к получению меньше уже записанных платежей. Сначала проверь платежи или добавь возврат.');}
  if(kind==='payment'||kind==='expense')d.amount=+d.amount;
  if(kind==='payment')paymentChecks(d,old);
  if(kind==='time')d.minutes=+d.minutes;
  if(kind==='task'){d.done=old?.data.done||false;d.title=d.title.trim();}
  if(d.orderId&&!rec(d.orderId))throw Error('Связанный заказ больше не существует. Обнови кабинет.');
  const saved=await put(user,kind,d,old);records=records.filter(r=>r.id!==saved.id).concat(saved);$('#editor').close();render();setSync('Сохранено');toast('Запись сохранена');
 }catch(e){$('#editor-error').textContent=errorText(e);setSync('Ошибка сохранения',true);}finally{busy=false;$('#editor-save').disabled=false;}
}
async function deleteRecord(){if(busy||!deleting)return;busy=true;$('#confirm-delete').disabled=true;const old=deleting;try{if(old.kind==='payment'){const current=rows(records,'payment').filter(p=>p.id!==old.id&&p.orderId===old.data.orderId),net=current.reduce((a,p)=>round(a+(p.type==='refund'?-p.amount:p.amount)),0);const o=orders().find(x=>x.id===old.data.orderId);if(net<0||o&&net>orderStats(o,records).net)throw Error('Удаление нарушит баланс поступлений и возвратов. Сначала исправь связанные платежи.');}await remove(old);records=records.filter(r=>r.id!==old.id);$('#confirm').close();if($('#editor').open)$('#editor').close();render();toast('Запись удалена');}catch(e){toast(errorText(e),true);}finally{busy=false;$('#confirm-delete').disabled=false;deleting=null;}}
function askDelete(id){if(demo)return toast('В примере удаление недоступно');const old=rec(id);if(!old)return;if(old.kind==='order'&&records.some(r=>['payment','expense','time','task'].includes(r.kind)&&r.data.orderId===id))return toast('У заказа есть связанные платежи, расходы, время или задачи. Используй статус «Отменен», чтобы сохранить историю.',true);deleting=old;$('#confirm-text').textContent=old.kind==='order'?`«${old.data.title}» будет удален без возможности отмены. Ты можешь вместо удаления выбрать статус «Отменен».`:'Запись будет удалена. Показатели кабинета пересчитаются.';$('#confirm').showModal();}
async function refresh(show=true){if(demo)return;if(refreshing||busy)return;if(!user)return;refreshing=true;const generation=sessionGeneration;setSync('Обновление');try{const next=await load();if(generation!==sessionGeneration||demo)return;records=next;loaded=true;if(!$('#editor').open)render();setSync('Синхронизировано');if(show)toast('Данные обновлены');}catch(e){if(generation!==sessionGeneration)return;setSync('Нет связи',true);if(show)toast(errorText(e),true);if(!loaded)render();}finally{refreshing=false;}}
function download(content,type,name){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function authScreen(){sessionGeneration++;user=null;records=[];loaded=false;demo=false;$('#app').hidden=true;$('#auth').hidden=false;$('#editor').close();$('#confirm').close();setAuthMode('login');}
async function enter(session){if(!session?.user||session.user.is_anonymous){authScreen();return;}sessionGeneration++;user=session.user;demo=false;records=[];loaded=false;$('#auth').hidden=true;$('#app').hidden=false;$('#demo-banner').hidden=true;$('#content').innerHTML='<div class="card"><p class="muted">Загружаем твой кабинет...</p></div>';await refresh(false);}
function setAuthMode(mode){authMode=mode;$('#auth-error').textContent='';$('#password-label').hidden=['recover','verify-signup','verify-recovery'].includes(mode);$('#password').required=!['recover','verify-signup','verify-recovery'].includes(mode);$('#password').autocomplete=mode==='signup'||mode==='new-password'?'new-password':'current-password';$('#otp-label').hidden=!mode.startsWith('verify');$('#otp').required=mode.startsWith('verify');$('#auth-title').textContent=({login:'Войти в кабинет',signup:'Создать аккаунт',recover:'Восстановить доступ','verify-signup':'Подтвердить email','verify-recovery':'Код восстановления','new-password':'Новый пароль'})[mode];$('#auth-submit').textContent=({login:'Войти',signup:'Создать аккаунт',recover:'Отправить письмо','verify-signup':'Подтвердить','verify-recovery':'Подтвердить код','new-password':'Сохранить пароль'})[mode];$('#auth-toggle').textContent=mode==='login'?'Создать аккаунт':'Вернуться ко входу';$('#auth-note').textContent=mode==='login'?'Подойдет аккаунт твоего планировщика. Данные доступны только тебе.':mode==='signup'?'Email и пароль будут использоваться на всех твоих устройствах.':mode==='recover'?'Пришлем письмо на email твоего аккаунта.':mode.startsWith('verify')?'Открой письмо: перейди по ссылке или введи код, если он указан. После подтверждения email вернись и войди.':'Задай новый пароль не менее 8 символов.';}
async function authSubmit(event){event.preventDefault();$('#auth-submit').disabled=true;$('#auth-error').textContent='';const email=$('#email').value.trim(),password=$('#password').value,otp=$('#otp').value.trim();try{let result;
 if(authMode==='login')result=await db.auth.signInWithPassword({email,password});
 else if(authMode==='signup'){result=await db.auth.signUp({email,password,options:{emailRedirectTo:location.href.split('#')[0]}});if(result.error)throw result.error;if(!result.data.session){setAuthMode('verify-signup');toast('Проверь письмо для подтверждения email');return;}}
 else if(authMode==='recover'){result=await db.auth.resetPasswordForEmail(email,{redirectTo:location.href.split('#')[0]});if(result.error)throw result.error;setAuthMode('verify-recovery');toast('Если аккаунт существует, письмо будет отправлено');return;}
 else if(authMode.startsWith('verify')){const recovery=authMode==='verify-recovery';let params={email,token:otp,type:recovery?'recovery':'signup'};if(/^https?:\/\//.test(otp)){const link=new URL(otp);if(link.origin!==CONFIG.url)throw Error('Вставь ссылку подтверждения из письма кабинета.');const hash=link.searchParams.get('token_hash')||link.searchParams.get('token');if(!hash)throw Error('В ссылке не найден код подтверждения');params={token_hash:hash,type:recovery?'recovery':'signup'};}result=await db.auth.verifyOtp(params);if(result.error)throw result.error;if(recovery){$('#email').value=result.data.user?.email||email;setAuthMode('new-password');return;}}
 else if(authMode==='new-password'){result=await db.auth.updateUser({password});if(result.error)throw result.error;toast('Пароль обновлен');const {data}=await db.auth.getSession();await enter(data.session);return;}
 if(result?.error)throw result.error;if(result?.data?.session)await enter(result.data.session);
 }catch(e){$('#auth-error').textContent=errorText(e);}finally{$('#auth-submit').disabled=false;}}
async function logout(){if(demo)return authScreen();try{const {error}=await db.auth.signOut();if(error)throw error;authScreen();}catch(e){toast(errorText(e),true);}}
async function action(action,id){
 if(action==='nav'){if(!VIEWS[id])return;view=id;render();window.scrollTo(0,0);return;}
 if(action==='refresh')return refresh();if(action==='logout')return logout();
 if(['order','payment','expense','time','task'].includes(action))return openEditor(action,action==='order'?id:'',action==='order'?'':id);
 if(action.startsWith('related-')){if($('#editor-form').dataset.dirty==='true')return toast('Сначала сохрани изменения карточки',true);$('#editor').close();return openEditor(action.slice(8),'',id);}
 if(action==='edit-record'){const r=rec(id);if(r)openEditor(r.kind,id);return;}
 if(action==='delete')return askDelete(id);
 if(action==='finance-tab'){financeTab=id;render();return;}if(action==='task-tab'){taskTab=id;render();return;}
 if(action==='csv')return download(csv(records),'text/csv;charset=utf-8',`Delo_zakazy_${dateISO()}.csv`);
 if(action==='export')return download(JSON.stringify({format:'workdesk',version:1,exportedAt:new Date().toISOString(),records:records.map(({id,kind,data})=>({id,kind,data}))},null,2),'application/json',`Delo_backup_${dateISO()}.json`);
 if(action==='toggle-task'){if(demo)return toast('Пример доступен для просмотра');if(busy)return;const old=rec(id);if(!old)return;busy=true;try{const saved=await put(user,'task',{...old.data,done:!old.data.done},old);records=records.filter(r=>r.id!==id).concat(saved);render();toast(saved.data.done?'Задача выполнена':'Задача возвращена в работу');}catch(e){toast(errorText(e),true);}finally{busy=false;}}
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;e.preventDefault();void action(b.dataset.action,b.dataset.id||'').catch(e=>toast(errorText(e),true));});
document.addEventListener('input',e=>{if(e.target.id?.startsWith('calc-'))calculateQuote();if(e.target.closest('#editor-form'))$('#editor-form').dataset.dirty='true';});
let searchTimer;document.addEventListener('input',e=>{if(e.target.id==='order-search'||e.target.id==='task-search'){const target=e.target,start=target.selectionStart;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if(target.id==='order-search')filter=target.value;else taskSearch=target.value;render();const next=$('#'+target.id);next.focus();next.setSelectionRange(start,start);},180);}});
document.addEventListener('change',e=>{if(e.target.id==='status-filter'){statusFilter=e.target.value;render();}if(e.target.id==='category-filter'){categoryFilter=e.target.value;render();}});
$('#period').value=period;$('#period').addEventListener('change',e=>{if(/^\d{4}-\d{2}$/.test(e.target.value)&&+e.target.value.slice(5)<=12){period=e.target.value;render();}});
$('#new-order').addEventListener('click',()=>openEditor('order'));$('#refresh').addEventListener('click',()=>refresh());$('#logout').addEventListener('click',logout);
$('#editor-form').addEventListener('submit',saveEditor);$('#editor').addEventListener('close',()=>{$('#editor-form').dataset.dirty='false';});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{if(!busy)$('#editor').close();}));$('#editor').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('#confirm-delete').addEventListener('click',deleteRecord);$('#cancel-delete').addEventListener('click',()=>{$('#confirm').close();deleting=null;});
document.addEventListener('submit',async e=>{if(e.target.id!=='settings-form')return;e.preventDefault();if(demo)return toast('Настройки примера не сохраняются');if(busy)return;busy=true;const b=e.target.querySelector('button');b.disabled=true;const values=Object.fromEntries(new FormData(e.target)),data={name:values.name.trim(),goal:+values.goal,hourly:+values.hourly,weeklyHours:+values.weeklyHours,categories:[...new Set(values.categories.split('\n').map(s=>s.trim()).filter(Boolean))]};try{const saved=await put(user,'settings',data,records.find(r=>r.kind==='settings'));records=records.filter(r=>r.kind!=='settings').concat(saved);render();toast('Настройки сохранены');}catch(err){$('#settings-error').textContent=errorText(err);}finally{busy=false;b.disabled=false;}});
$('#auth-form').addEventListener('submit',authSubmit);$('#auth-toggle').addEventListener('click',()=>setAuthMode(authMode==='login'?'signup':'login'));$('#auth-forgot').addEventListener('click',()=>setAuthMode('recover'));
$('#demo').addEventListener('click',()=>{sessionGeneration++;demo=true;loaded=true;records=demoRecords();view='overview';$('#auth').hidden=true;$('#app').hidden=false;$('#demo-banner').hidden=false;setSync('Пример');render();});$('#demo-exit').addEventListener('click',authScreen);
window.addEventListener('focus',()=>{if(!$('#editor').open&&!$('#confirm').open)refresh(false);});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&!$('#editor').open)refresh(false);});setInterval(()=>{if(document.visibilityState==='visible'&&!$('#editor').open&&!$('#confirm').open)refresh(false);},30000);
window.addEventListener('beforeunload',e=>{if($('#editor').open&&$('#editor-form').dataset.dirty==='true'){e.preventDefault();e.returnValue='';}});
db.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){user=session?.user;$('#email').value=session?.user?.email||'';$('#app').hidden=true;$('#auth').hidden=false;setAuthMode('new-password');}else if(event==='SIGNED_OUT'&&!demo)authScreen();else if(event==='TOKEN_REFRESHED'&&session)user=session.user;else if(event==='SIGNED_IN'&&user&&session?.user.id!==user.id&&!demo)setTimeout(()=>enter(session),0);});
if(document.modelContext?.registerTool){const tools=[{name:'read_workdesk_summary',title:'Показатели кабинета',description:'Читает показатели за выбранный месяц из открытого кабинета.',inputSchema:{type:'object',properties:{month:{type:'string',pattern:'^\\d{4}-(0[1-9]|1[0-2])$'}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async input=>{if(!loaded)throw Error('Сначала войди в кабинет');const month=input?.month||period;if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw Error('Некорректный месяц');return {month,demo,...metrics(records,month)};}},{name:'start_workdesk_order',title:'Открыть новый заказ',description:'Открывает форму нового заказа. Не сохраняет заказ.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(Object.keys(input||{}).length)throw Error('Лишние параметры');if(!user||demo)throw Error('Войди в свой аккаунт');openEditor('order');return {opened:$('#editor').open};}}];for(const tool of tools)try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}
try{const {data,error}=await db.auth.getSession();if(error)throw error;if(data.session&&authMode!=='new-password')await enter(data.session);}catch(e){$('#auth-error').textContent=errorText(e);}
